Ci
ralphVenancio/faast-foundations pull request #3
Opened 2023-03-22 12:51 UTC by ralphVenancio

2023-04-04 09:16 UTC, rfmmonteiro99 requested changes
Good work, Ralph :)

Like I commented in the review, I think you just need to update the workflow pipeline and linting/structure of your cleaning.py file

2023-04-04 09:16 UTC, rfmmonteiro99 commented on assignments_01/cleaning.py
> +            unit, sex, age, region, year, value.
Also, to lint your code, you could add the type for each parameter, like: `df_to_clean: pd.DataFrame`

And also what type the function returns at the end, like  `-> pd.DataFrame`

2023-04-04 09:16 UTC, rfmmonteiro99 commented on assignments_01/cleaning.py
> +    def clean_data(self, df_to_clean):
```suggestion
    def clean_data(
        self, 
        df_to_clean: pd.DataFrame
    ) -> pd.DataFrame:
```

2023-04-04 09:16 UTC, rfmmonteiro99 commented on assignments_01/cleaning.py
>      def main(self):
I think in the main function you should use argparse to pass `region` as an argument, instead of setting it as 'PT' in the clean_data function

2023-04-26 15:35 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +    def load_data(self):
```suggestion
    def load_data(self) -> pd.DataFrame:
```

2023-04-26 15:35 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +        '''
```suggestion
    def clean_data(self, df_to_clean: pd.DataFrame) -> pd.DataFrame:
        ''' 
        This function unpivots data to long format, so that it have the following columns:
            unit, sex, age, region, year, value.
            
        '''
```

2023-05-01 20:28 UTC, merged